# Generated by Django 4.0.5 on 2022-06-10 15:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_fueltype_residence_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='SportingGood',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
            ],
            bases=('listings.item',),
        ),
        migrations.AddField(
            model_name='residence',
            name='lease_duration',
            field=models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.item')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.clothingtype')),
            ],
            bases=('listings.item',),
        ),
    ]
