# Generated by Django 4.0.5 on 2022-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_book_clothingtype_electronic_furniture_job_misc_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='messages_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
